config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :categories
  end

  resources :categories
  resources :admins
  root "books#list"
  get 'books/new'
  get 'categories/new'
  get 'admins/show'
  post "/auth", to: 'admins#auth'
  post "/search",to: 'books#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  public
  def index
    @books=Book.all
    @categories=Category.all
    @is_logged=true
  end
  def show
    @admin=Admin.new
  end
  def auth
    @username=params[:username].to_s
    @password=params[:password].to_s
    @admin=Admin.find_by(username: @username)
    @is_logged=false
    if @admin.blank?
      render 'admins/error'
    else
      if @password==@admin.password
        @is_logged=true
        @books=Book.all
        @categories=Category.all
        redirect_to :action =>  'index'
      else
        render 'admins/error'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def list
    @books=Book.all
    @categories=Category.all
  end
  def show
    @book=Book.find(params[:id])
    @category=Category.find(@book.category_id)
    if params[:logged]=="true"
      @is_logged=true
    else
      @is_logged=false
    end
  end
  def new
    @book=Book.new
    @categories=Category.all
  end
  def book_params
    params.require(:book).permit(:title, :category_id, :author, :published_date, :price, :description)
  end
  def create
    @book=Book.new(book_params)
    if @book.save
      redirect_to :controller => 'admins', :action => 'index'
    else
      @categories=Category.all
      render :action => 'new'
    end
  end
  def edit
    @book = Book.find(params[:id])
    @categories = Category.all
  end
  def update
    @book = Book.find(params[:id])
    @is_logged=true
    if @book.update(book_params)
      redirect_to :controller => 'admins', :action => 'index'
    else
      @categories = Category.all
      render :action => 'edit'
    end
  end
  def destroy
    Book.find(params[:id]).destroy
    redirect_to :controller => 'admins', :action => 'index'
  end
  def show_categories
    @categories = Category.find(params[:id])
  end
  def search
    if params[:logged][0]=='true'
      @is_logged=true
    else
      @is_logged=false
    end
    @category_id=params[:category][:category_id]
    @books=Book.where(category_id: @category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def list
    @categories=Category.all
  end
  def new
    @category=Category.new
  end
  def show
    @category=Category.find(params[:id])
  end
  def create
    @category=Category.new(category_params)
    if @category.save
      redirect_to :controller => 'admins', :action => 'index'
    else
      @categories=Category.all
      render :action => 'new'
    end
  end
  def category_params
    params.require(:category).permit(:name)
  end
  def edit
    @category=Category.find(params[:id])
    @categories= Category.all
  end
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to :controller => 'admins', :action => 'index'
    else
      @categories = Category.all
      render :action => 'edit'
    end
  end
  def destroy
    Category.find(params[:id]).destroy
    redirect_to :controller => 'admins', :action => 'index'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admins/error.html.erb
<h1>Error</h1>
<%= link_to "Login", :action => 'show'%>

app/views/admins/index.html.erb
<h1 style="text-align: center">Welcome to Admin Console of Book Catalogue App</h1>
<div style="text-align: center">
  <%= form_tag "/search" do %>
    <div>
      <p><%= label_tag(:category, "Search By Category") %></p>
      <p><%= collection_select(:category,:category_id, @categories, :id, :name) %></p>
      <p><%=hidden_field(:logged, nil, :value=>true) %></p>
    </div>
    <%= submit_tag "Search" %>
  <% end %>
</div>
<div style="margin:0 auto">
  <% if @books.blank? %>
    <p>There are not any books currently in the
      system.</p>
  <% else %>
    <p>These are the current books in our
      system</p>
    <ul id="books">
      <% @books.each do |b| %>
        <li>
          <%= b.title %> |
          <%= link_to "Show", {:controller=>'books',:action => 'show', :id => b.id, :logged=>true} %>|
            <%= link_to "Edit", {:controller=>'books',:action => 'edit', :id => b.id} %> |
            <%= link_to "Delete", book_path(b), :controller=>'books', method: 'delete', data: { confirm: 'Are you sure?'} %> |
        </li>
      <% end %>
    </ul>
  <% end %>
  <% if @categories.blank? %>
    <p>There are not any categories currently in the
      system.</p>
  <% else %>
    <p>These are the current categories in our
      system</p>
    <ul id="categories">
      <% @categories.each do |c| %>
        <li>
          <%= c.name %> |
          <%= link_to "Edit", {:controller=>'categories',:action => 'edit', :id => c.id} %> |
          <%= link_to "Delete", category_path(c), :controller=>'categories', method: 'delete', data: { confirm: 'Are you sure?'} %> |
        </li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= link_to "Add new Book", {:controller=>'books',:action => 'new' }%>
  </p>
  <p>
    <%= link_to "Add new Category", {:controller=>'categories',:action => 'new' }%>
  </p>
  <p>
    <%= link_to "Logout", :controller => 'books', :action => 'list'%>
  </p>
</div>

app/views/admins/show.html.erb
<div>
  <%= form_tag "/auth" do %>
    <div>
      <p><%= label_tag(:username, "Username") %></p>
      <p><%= text_field_tag(:username, nil) %></p>
      <p><%= label_tag(:password, "Password") %></p>
      <p><%= text_field_tag(:password, nil) %></p>
    </div>
    <%= submit_tag "Login" %>
  <% end %>
</div>

app/views/admins/success.html.erb
<h1>Welcome Admin</h1>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= form_for(@book) do |b| %>
  <p><%= b.label :title %>
    <%= b.text_field :title %> </p>
  <p> <%= b.label :category %>
    <%= collection_select(:book,:category_id, @categories, :id, :name) %></p>
  <p><%= b.label :author %>
    <%= b.text_field :author %> </p>
  <p><%= b.label :published_date %>
    <%= b.text_field :published_date %> </p>
  <p><%= b.label :price %>
    <%= b.text_field :price %> </p>
  <p><%= b.label :description %>
    <%= b.text_field :description %> </p>
  <%= b.submit %>
<% end %>
<%= link_to 'Back', {:controller => 'admins', :action => 'index'}%>

app/views/books/list.html.erb
<h1 style="text-align: center">Welcome to Book Catalogue App</h1>
<div style="text-align: center">
  <%= form_tag "/search" do %>
    <div>
      <p><%= label_tag(:category, "Search By Category") %></p>
      <p><%= collection_select(:category,:category_id, @categories, :id, :name) %></p>
<!--      <p><%#= text_field_tag(:category, nil) %></p>-->
      <p><%=hidden_field(:logged, nil, :value=>false) %></p>
    </div>
    <%= submit_tag "Search" %>
  <% end %>
</div>
<div style="margin:0 auto">
<% if @books.blank? %>
  <p>There are not any books currently in the
    system.</p>
<% else %>
  <p>These are the current books in our
    system</p>
  <ul id="books">
    <% @books.each do |b| %>
      <li>
        <%= b.title %> |
        <%= link_to "Show", {:controller=>'books',:action => 'show', :id => b.id, :logged=>false} %>|
      </li>
    <% end %>
  </ul>
<% end %>
<% if @categories.blank? %>
  <p>There are not any categories currently in the
    system.</p>
<% else %>
  <p>These are the current categories in our
    system</p>
  <ul id="categories">
    <% @categories.each do |c| %>
      <li>
        <%= c.name %>
      </li>
    <% end %>
  </ul>
<% end %>
<p>
<%#if $is_logged %>
  <%#= link_to "Add new Book", {:controller=>'books',:action => 'new' }%>
  <%#= link_to "Logout", :controller => 'books', :action => 'list'%>
  <%#else %>
<%= link_to "Login", :controller => 'admins', :action => 'show'%>
<%#end %>
</p>
</div>

app/views/books/new.html.erb
<h1>Add new book</h1>
<%= form_for(@book) do |b| %>
  <p><%= b.label :title %>
    <%= b.text_field :title %> </p>
  <p> <%= b.label :category %>
    <%= collection_select(:book,:category_id, @categories, :id, :name) %></p>
  <p><%= b.label :author %>
    <%= b.text_field :author %> </p>
  <p><%= b.label :published_date %>
    <%= b.text_field :published_date %> </p>
  <p><%= b.label :price %>
    <%= b.text_field :price %> </p>
  <p><%= b.label :description %>
    <%= b.text_field :description %> </p>
  <%= b.submit %>
<% end %>
<%= link_to 'Back', {:controller => 'admins', :action => 'index'}%>

app/views/books/search.html.erb
<h1 style="text-align: center">Searched Books</h1>
<% if @books.blank? %>
  <p>There are not any books in this Catgeory.</p>
<% else %>
  <p>These are the current books with Category <%=@category_name %></p>
  <ul id="books">
    <% @books.each do |b| %>
      <li>
        <%= b.title %> |
        <%= link_to "Show", {:controller=>'books',:action => 'show', :id => b.id, :logged=>@is_logged} %>|
      </li>
    <% end %>
  </ul>
<% end %>
<%if @is_logged%>
  <%= link_to 'Back', {:controller => 'admins', :action => 'index'} %>
<%else %>
  <%= link_to 'Back', {:controller => 'books', :action => 'list'} %>
<%end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1> <p>
  <strong>Price: </strong>
  $<%= @book.price %><br />
  <strong>Category :</strong>
  <%= @category.name %><br />
  <strong>Author :</strong>
  <%= @book.author %><br />
  <strong>Published Date:</strong>
  <%= @book.published_date %><br />
  <strong>Description :</strong>
  <%= @book.description %><br />
</p>


<hr />
<%if @is_logged%>
  <%= link_to 'Back', {:controller => 'admins', :action => 'index'} %>
<%else %>
  <%= link_to 'Back', {:controller => 'books', :action => 'list'} %>
<%end %>

app/views/categories/edit.html.erb
<h1>Edit category</h1>
<%= form_for(@category) do |c| %>
  <p><%= c.label :name %>
    <%= c.text_field :name %> </p>
  <%= c.submit %>
<% end %>
<%= link_to 'Back', {:controller => 'admins', :action => 'index'}%>

app/views/categories/new.html.erb
<h1>Add new category</h1>
<%= form_for(@category) do |c| %>
  <p><%= c.label :name %>
    <%= c.text_field :name %> </p>
  <%= c.submit %>
<% end %>
<%= link_to 'Back', {:controller => 'admins', :action => 'index'}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCatalogueApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>